publish_to: https://pub.dev

name: robots_txt
version: 1.1.0+2

description: >-
  A simple yet complete, lightweight and sturdy `robots.txt` ruleset parser
  to ensure your application follows the standard protocol.

homepage: https://github.com/wordcollector/robots_txt
repository: https://github.com/wordcollector/robots_txt
issue_tracker: https://github.com/wordcollector/robots_txt/issues

environment:
  sdk: '>=2.13.0 <3.0.0'

dependencies:
  sprint: ^1.0.2+4
  web_scraper: ^0.1.4

dev_dependencies:
  words: ^0.0.2+1
